# Site settings
title: Chloe Atchue-Mamlet
email: chloe793@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio and blog of Chloe Atchue-Mamlet

# Social media
twitter_username: chloe793
github_username:  chloeam

# Build settings

markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css
  style: :nested